"""job filters

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-27 12:15:44.666061
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_globs', sa.Text(), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('exclude_globs', sa.Text(), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('max_file_size', sa.BigInteger(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_column('max_file_size')
        batch_op.drop_column('exclude_globs')
        batch_op.drop_column('include_globs')

    # ### end Alembic commands ###
