"""job schedule windows

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-05 19:50:55.045998
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_hours', sa.Text(), server_default=sa.text("'111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111'"), nullable=False))
        batch_op.add_column(sa.Column('stop_outside_window', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_hours', sa.Text(), server_default=sa.text("'111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111'"), nullable=False))
        batch_op.add_column(sa.Column('stop_outside_window', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_column('stop_outside_window')
        batch_op.drop_column('schedule_hours')

    with op.batch_alter_table('download_jobs', schema=None) as batch_op:
        batch_op.drop_column('stop_outside_window')
        batch_op.drop_column('schedule_hours')

    # ### end Alembic commands ###
