"""deletion guard on sync jobs

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-05 21:27:27.138755
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_guard_percent', sa.Integer(), server_default=sa.text('(20)'), nullable=False))
        batch_op.add_column(sa.Column('delete_guard_files', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('delete_guard_bypass', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_column('delete_guard_bypass')
        batch_op.drop_column('delete_guard_files')
        batch_op.drop_column('delete_guard_percent')

    # ### end Alembic commands ###
