"""trash with retention

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-05 21:32:32.680741
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trashed_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trashed', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('revived', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trash_days', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_column('trash_days')

    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_column('revived')
        batch_op.drop_column('trashed')

    with op.batch_alter_table('file_entries', schema=None) as batch_op:
        batch_op.drop_column('trashed_at')

    # ### end Alembic commands ###
