"""bandwidth limit per job

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-05 21:44:28.748488
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('throttle_bps', sa.BigInteger(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('throttle_bps', sa.BigInteger(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_column('throttle_bps')

    with op.batch_alter_table('download_jobs', schema=None) as batch_op:
        batch_op.drop_column('throttle_bps')

    # ### end Alembic commands ###
