"""silence alarm on jobs

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-05 21:49:10.916680
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('silence_alerts', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('silence_alerted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('silence_alerts', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('silence_alerted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_column('silence_alerted_at')
        batch_op.drop_column('silence_alerts')

    with op.batch_alter_table('download_jobs', schema=None) as batch_op:
        batch_op.drop_column('silence_alerted_at')
        batch_op.drop_column('silence_alerts')

    # ### end Alembic commands ###
