"""scheduled channel checks

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-05 21:52:03.944579
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0009'
down_revision: str | None = '0008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_interval_days', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('check_hour', sa.Integer(), server_default=sa.text('4'), nullable=False))
        batch_op.add_column(sa.Column('check_repair', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_check_result', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_column('last_check_result')
        batch_op.drop_column('last_check_at')
        batch_op.drop_column('check_repair')
        batch_op.drop_column('check_hour')
        batch_op.drop_column('check_interval_days')

    # ### end Alembic commands ###
