"""runs remember how often Telegram held them back

Revision ID: 0010
Revises: 0009
Create Date: 2026-08-12 17:00:04.267650
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0010'
down_revision: str | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limited_events', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limited_events', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_column('limited_events')

    with op.batch_alter_table('download_runs', schema=None) as batch_op:
        batch_op.drop_column('limited_events')

    # ### end Alembic commands ###
