"""connection budget per account

Revision ID: 0011
Revises: 0010
Create Date: 2026-08-12 19:50:03.904180
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0011'
down_revision: str | None = '0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_connections', sa.Integer(), server_default=sa.text('(15)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_accounts', schema=None) as batch_op:
        batch_op.drop_column('max_connections')

    # ### end Alembic commands ###
