"""bot sets

Two new tables and three columns. The tables are new, so a database with rows goes
through them untouched; what has to be watched is the two `account_id` columns becoming
nullable, which SQLite can only do by rebuilding the table around the change. That is what
`render_as_batch` is on for, and what `check_migrations.py` proves by seeding a row into
every table before upgrading.

A channel with no account is one a bot set named by itself, which is the only way to reach
a channel on an installation that has never linked an account. A job with no account is one
that runs on a set: exactly one of the two columns carries it, enforced by the API rather
than by the DDL, since a check constraint added here would have to be rebuilt again the
next time either column moves.

Revision ID: 0012
Revises: 0011
Create Date: 2026-08-12 20:49:00.141427
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0012'
down_revision: str | None = '0011'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_hash_enc', sa.Text(), nullable=False),
    sa.Column('max_connections', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=False),
    sa.Column('default_part_size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_set_id', sa.Integer(), nullable=False),
    sa.Column('token_enc', sa.Text(), nullable=False),
    sa.Column('session_enc', sa.Text(), nullable=True),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_set_id'], ['bot_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_set_id', 'tg_id', name='uq_bot_set_tg')
    )
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_set_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parallel_files', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(
            'fk_sync_jobs_bot_set', 'bot_sets', ['bot_set_id'], ['id'], ondelete='CASCADE'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sync_jobs_bot_set', type_='foreignkey')
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('parallel_files')
        batch_op.drop_column('bot_set_id')

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('bots')
    op.drop_table('bot_sets')
    # ### end Alembic commands ###
